apiVersion: apps/v1                         # apiVersion may vary depending on your eks cluster version
kind: Deployment                            # Api resource type
metadata:
  name: example-frontend-deployment         # Name of the deployment
  labels:
    app: example-frontend                   # Labels that are applied to this deployment
  namespace: frontend                       # Namespace where this deployment will be deployed
spec:
  replicas: 0                               # Number of pods current deployment will create
  selector:
    matchLabels:
      app: example-frontend                 # Labels which a deployment will look for
  strategy:
    rollingUpdate:                          
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate                     # Deployment option, either replace pods all at once or partially
  minReadySeconds: 30                       # After the pod becomes ready state, it waits 30 seconds for the pod to be completely functional
  template:
    metadata:
      labels:
        app: example-frontend               # Labels which will be applied to the pod
    spec:
      containers:
      - image: {$account_id.dkr.ecr.ap-northeast-2.amazonaws.com}/{$repository_name}:{$image_name}   # Image URI of Image that is located in ECR repo
        name: example-frontend              # Container name
        ports:
        - containerPort: 3000               # Port that container is currently listening on
          protocol: TCP                     # Network type
        resources:
          requests:                         # Resource that pod will require
            cpu: 100m
            memory: 150Mi
          limits:                           # Maximum capacity the pod can use
            cpu: 150m
            memory: 200Mi
      tolerations:                          # If certain nodes have taints, toleration enables pods to bypass the taints
      - key: "frontend-workload"
        operator: "Equal"
        effect: "NoSchedule"
      - key: "backend-workload"
        operator: "Equal"
        effect: "NoSchedule"
      - key: "karpenter-front"
        operator: "Equal"
        effect: "NoSchedule"
