apiVersion: v1                              
kind: Service                         # Type of api resource
metadata:
  name: example-frontend-service      # Name of the service
  namespace: frontend                 # Namespace in which the service will be created
spec:
  selector:
    app: example-frontend             # Tags which service will look for in pods
  type: ClusterIP                     # Type of the service(ClusterIP, NodePort, LoadBalancer)
  ports:
   -  protocol: TCP                   # Network type
      port: 443                       # Port which service is listening externally(Ingress)
      targetPort: 3000                # Port which service is listening internally(Pods)
