apiVersion: apps/v1
kind: Deployment
metadata:
  name: inflate-frontend
spec:
  replicas: 0
  selector:
    matchLabels:
      app: inflate-frontend
  template:
    metadata:
      labels:
        app: inflate-frontend
    spec:
      terminationGracePeriodSeconds: 0
      containers:
        - name: inflate
          image: public.ecr.aws/eks-distro/kubernetes/pause:3.7
          resources:
            requests:                         # Amount of cpu that pod will be assigned to
              cpu: 1
      tolerations:                            # Toleration that bypasses taints that are applied to nodes
      - key: "frontend-workload"
        operator: "Equal"
        effect: "NoSchedule"
