apiVersion: karpenter.sh/v1alpha5
kind: Provisioner
metadata:
  name: default
spec:
  requirements:
    - key: karpenter.k8s.aws/instance-category
      operator: In
      values: [t, c]
    - key: karpenter.sh/capacity-type
      operator: In
      values: [on-demand]
    - key: karpenter.k8s.aws/instance-size
      operator: In
      values: [nano, micro, small, medium, large]
    - key: kubernetes.io/arch
      operator: In
      values: [amd64]
    - key: topology.kubernetes.io/zone
      operator: In
      values: [ap-northeast-2a, ap-northeast-2c]
  limits:
    resources:
      cpu: 500
      memory: 500Gi
  ttlSecondsAfterEmpty: 30
  ttlSecondsUntilExpired: 2592000
  providerRef:
    name: default
---
apiVersion: karpenter.k8s.aws/v1alpha1
kind: AWSNodeTemplate
metadata:
  name: default
spec:
  subnetSelector:
    karpenter.sh/discovery: carflix-cluster
  securityGroupSelector:
    karpenter.sh/discovery: carflix-cluster
  tags:
    KarpenerProvisionerName: "carflix-cluster-karpenter-provisioner"
    NodeType: "carflix-cluster"
